export const AuditLogAction = {
  // Meetup
  MEETUP_CREATE: 1,
  MEETUP_EDIT: 2,
  MEETUP_DELETE: 3,

  // Participations
  MEETUP_PARTICIPANT_ADD: 10,
  MEETUP_PARTICIPANT_REMOVE: 11,
  MEETUP_PARTICIPANT_UNSURE_ENABLE: 12,
  MEETUP_PARTICIPANT_UNSURE_DISABLE: 13,
  MEETUP_PARTICIPANT_REMOTE_ENABLE: 14,
  MEETUP_PARTICIPANT_REMOTE_DISABLE: 15,

  // Meetup mention roles
  MEETUP_MENTION_ROLE_ADD: 20,
  MEETUP_MENTION_ROLE_REMOVE: 21,

  // Notices
  NOTICE_CREATE: 30,
  NOTICE_EDIT: 31,
  NOTICE_DELETE: 32,

  // Cronjobs
  CRON_HOURLY_RUN: 40,
  CRON_HOURLY_SUCCESS: 41,
  CRON_HOURLY_ERROR: 42,
  CRON_DAILY_RUN: 43,
  CRON_DAILY_SUCCESS: 44,
  CRON_DAILY_ERROR: 45,
} as const;

export type AuditLogAction = typeof AuditLogAction[keyof typeof AuditLogAction];