export const AuditLogAction = {
  // Meetup
  MEETUP_CREATE: 1,
  MEETUP_EDIT: 2,
  MEETUP_DELETE: 3,

  // Participations
  MEETUP_PARTICIPANT_JOIN: 10,
  MEETUP_PARTICIPANT_LEAVE: 11,
  MEETUP_PARTICIPANT_ADD_ADDITIONAL: 12,
  MEETUP_PARTICIPANT_REMOVE_ADDITIONAL: 13,
  MEETUP_PARTICIPANT_UNSURE_ENABLE: 14,
  MEETUP_PARTICIPANT_UNSURE_DISABLE: 15,
  MEETUP_PARTICIPANT_REMOTE_ENABLE: 16,
  MEETUP_PARTICIPANT_REMOTE_DISABLE: 17,

  // Meetup roles
  MEETUP_ROLE_ADD: 20,
  MEETUP_ROLE_REMOVE: 21,

  // Notices
  NOTICE_CREATE: 30,
  NOTICE_EDIT: 31,
  NOTICE_DELETE: 32,

  // Cronjobs
  CRON_HOURLY_RUN: 40,
  CRON_DAILY_RUN: 41,
} as const;

export type AuditLogAction = typeof AuditLogAction[keyof typeof AuditLogAction];